### ISSUE TITLE
'corners' property has range 0 - 0.5 instead of 0 - 1.

### ISSUE THREAD

**Issue by IamfromSpace** [damienklinnert/elm-spinner#11]
Noticed that since the corners property multiplies by width (the diameter), 0.5 fully rounds the corners (since it uses radius) instead of 1, as implied by the docs.  Updating the docs would be simpler (no breaking change), but updating the code would give more natural results.  Or both could be done, one in a 3.0 and 4.0 release.

I'd be happy to open PR(s), but not sure the preferred strategy.

**Comment by damienklinnert** [comment]
Hey @IamfromSpace, I'd prefer to go with the more natural results - even if it means that we have to do a major version bump. Would love to see a pull request for that :)
