### ISSUE TITLE
Non-absolutely positioned spinners

### ISSUE THREAD

**Issue by mbr** [damienklinnert/elm-spinner#15]
Currently, `position: absolute` seems hardcoded into the Spinner. It would be nice if one could have many spinners laid out normally on the page.

**Comment by damienklinnert** [comment]
Thanks for your great question @mbr.

You can already place many spinners on the page, despite the `position: absolute`. Just position the spinner inside of a `div` with `position: relative`. This should position the spinner within that element. You can place as many spinners as you like that way.

Let me know how it goes.

**Comment by mbr** [comment]
My apologies. You are 100% correct and this issue should not have been filed. Sorry.
