### ISSUE TITLE
Changing direction to "Counterclockwise" in editor does nothing.

### ISSUE THREAD

**Issue by Heimdell** [damienklinnert/elm-spinner#4]
Subj.

**Comment by damienklinnert** [comment]
Hey @Heimdell thanks for reporting the issue!
I'd love to fix it asap, but I'm having problems reproducing it. Which browser did you use to trigger that behaviour?

**Comment by tbasse** [comment]
@damienklinnert, changing direction does not work in Firefox.

Looks like Firefox does not support `oninput` events for <select> elements.
https://bugzilla.mozilla.org/show_bug.cgi?id=312094
