### ISSUE TITLE
'scale' config option alters the ratio of radius/length/width

### ISSUE THREAD

**Issue by IamfromSpace** [damienklinnert/elm-spinner#9]
When configuring my spinner, I would expect that the scale parameter would not alter any of the ratios of height/width/radius--just to be a bigger or smaller version.  However, the look of the spinner is also altered when the scale is changed.

**Comment by damienklinnert** [comment]
Hey @IamfromSpace, good spot! It looks as if the length of the lines is not scaled accordingly. Would you be able to have a look at this and try to come up with a fix? :)

**Comment by IamfromSpace** [comment]
Happy to!  I'll try to get a PR open soon.
